version: "3.9"
services:
  pain-db:
    image: postgres
    restart: always
    container_name: pain-db
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - pain-network
networks:
  pain-network:
    driver: bridge
